### ISSUE TITLE
[EPIC] Build an eshop

### ISSUE THREAD

**Issue by techerjeansebastienpro** [grunera/orinocoESHOP#1]
**Stories**

- [ ] As a user, I can list all products for a fixed category: Name / Picture / Price
- [ ] As a user, I can click on a product item to see product details
- [ ] As a user, I can see a product details page : Name / description / product option select option / price
- [ ] As a user, I can select a product option on product details page
- [ ] As a user, I can add a configured product (product + option) in a shopping cart
- [ ] As a user, I can click on a shopping cart button, from anywhere, to see shopping cart details
- [ ] As a user, I can see a list of selected products (picture / name / unit price), and the amount (sum of prices) of the shopping cart 
- [ ] As a user, I can fill a form, and confirm an order
- [ ] As a user, I can see an order confirmation page

 
**Recommandations**

Use E-commerce API Project: add https://github.com/OpenClassrooms-Student-Center/JWDP5 as submodule
Use Request Params to communicate product id between list and details
Use Localstorage for shopping cart storage data
